name: qonnect
favicon: null
layout_spectrum: 1
typography_spectrum: 0.027854652609676123
title: qonnect
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a7a7a7'
    - '#000000'
    - '#3e3e3e'
    - '#707070'
  brandStrength: 0.375
  lightness: 0.6033130132127553
  saturation: 0.5874229439068586
  rhythmicContrast: 0.5
purpose: []
