name: qonnect
favicon: null
layout_spectrum: 0.3764918053057045
typography_spectrum: 0.027854652609676123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6bc694'
    - '#94d6b5'
    - '#63b58c'
    - '#c6e7d6'
    - '#f7f8f7'
  brandStrength: 0.25
  lightness: 0.6033130132127553
  saturation: 0.5874229439068586
  rhythmicContrast: 0.5
purpose: []
