name: qonnect
favicon: null
layout_spectrum: 0
typography_spectrum: 0.20374
title: qonnect
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a7a7a7'
    - '#000000'
    - '#3e3e3e'
    - '#707070'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
